### ISSUE TITLE
errors when running

### ISSUE THREAD

**Issue by elderwolf123** [MatthewPierson/PyBoot#16]
was trying it on an ipad 2,1 and it errord, i couldn't even enter pwnDFU
Current version is: Beta 0.2
Make sure your device is connected in DFU mode
Traceback (most recent call last):
  File "./pyboot.py", line 140, in <module>
    main()
  File "./pyboot.py", line 120, in main
    img4.img4stuff(argv[2], argv[3], useCustomLogo, logopath)
  File "/Users/tannerjarrod24/Desktop/PyBoot-master/resources/img4.py", line 163, in img4stuff
    'iPhone6,2': argv[3],  # Since these have all keys up, we can just use whatever the downgraded version is =)
NameError: name 'argv' is not defined
iMac:PyBoot-master tannerjarrod24$ ./pyboot.py -p
Traceback (most recent call last):
  File "./pyboot.py", line 140, in <module>
    main()
  File "./pyboot.py", line 92, in main
    pwn.pwndfumode()
  File "/Users/tannerjarrod24/Desktop/PyBoot-master/resources/pwn.py", line 10, in pwndfumode
    device = dfu.acquire_device()
  File "/Users/tannerjarrod24/Desktop/PyBoot-master/resources/ipwndfu/dfu.py", line 23, in acquire_device
    usb.util.claim_interface(device, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/util.py", line 205, in claim_interface
    device._ctx.managed_claim_interface(device, interface)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno None] Other error
iMac:PyBoot-master tannerjarrod24$

**Comment by MatthewPierson** [comment]
Should be fixed in latest commit, download latest files and try again please

**Comment by elderwolf123** [comment]
elderwolf123@jarrods-iMac PyBoot-master % ./pyboot.py -p 

Traceback (most recent call last):

  File "./pyboot.py", line 181, in <module>

    main()

  File "./pyboot.py", line 96, in main

    pwn.pwndfumode()

  File "/Users/elderwolf123/Desktop/PyBoot-master/resources/pwn.py", line 10, in pwndfumode

    device = dfu.acquire_device()

  File "/Users/elderwolf123/Desktop/PyBoot-master/resources/ipwndfu/dfu.py", line 20, in acquire_device

    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/usb/core.py", line 1263, in find

    raise NoBackendError('No backend available')

usb.core.NoBackendError: No backend available

elderwolf123@jarrods-iMac PyBoot-master %

**Comment by elderwolf123** [comment]
does Pyboot have support for A5's as that is susceptable to checkm8

**Comment by MatthewPierson** [comment]
Do you have libusb installed? If not, install it with brew. No it doesn't, only A7-A11

**Comment by elderwolf123** [comment]
well no point, the ipad has an A5 which is supported by check m8 but no one has made any tools for it
