### ISSUE TITLE
"The device has no langid" iPhone 6s Plus IOS 13.6 to IOS 13.5 dualbooting macOS 10.13.6

### ISSUE THREAD

**Issue by Lifr0m** [MatthewPierson/PyBoot#52]
I'm from Divise.

```
MacBook-Pro-Artem:PyBoot-master artemkaygorodtsev$ sudo ./pyboot.py -i iPhone8,2 13.5 -d disk0s1s7
Password:
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i

Current version is: Beta 0.9.1
User choose to boot 13.5 from /dev/disk0s1s7.
Make sure your device is connected in DFU mode
Checking theiphonewiki for 13.5 keys...
Found Keys!
Found a keys page with multiple models...
Which is your device?
1: N66AP
2: N66mAP
Enter 1 or 2: 2
User chose N66mAP, grabbing those keys...
Keys for the other device model are present but not for your model.
PyBoot will place your device into PWNDFU mode and retrieve the needed keys...
Please ensure your device is connected in DFU mode...
Traceback (most recent call last):
  File "./pyboot.py", line 505, in <module>
    main()
  File "./pyboot.py", line 477, in main
    img4.img4stuff(args.ios[0], args.ios[1], useCustomLogo, logopath, arewelocal, bootOtherOS, bootArgs, amfiPatches)
  File "/Users/artemkaygorodtsev/Desktop/PyBoot-master/resources/img4.py", line 262, in img4stuff
    pwndfumodeKeys()
  File "/Users/artemkaygorodtsev/Desktop/PyBoot-master/resources/pwn.py", line 33, in pwndfumodeKeys
    serial_number = device.serial_number
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/usb/core.py", line 830, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/usb/util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid
MacBook-Pro-Artem:PyBoot-master artemkaygorodtsev$ 
```

**Comment by Lifr0m** [comment]
this was because of my mbp late 2011...
