### ISSUE TITLE
  raise NoBackendError('No backend available') usb.core.NoBackendError: No backend available

### ISSUE THREAD

**Issue by efe-star** [MatthewPierson/PyBoot#61]
Hi When I try to boot tether with pyboot I am getting error. "usb.core.NoBackendError: No backend available"
I searched in web but I can't found anything. And Sorry about my English :(

My terminal output

sh-3.2# ./pyboot.py -i iPhone10,5 13.7 -b /Users/username/Desktop/apple-logo-n84@2x\~iphone.png 
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i

Current version is: Beta 0.9.1
Make sure your device is connected in DFU mode
Checking theiphonewiki for 13.7 keys...
Keys weren't found for your device, PyBoot will place your device into PWNDFU mode and retrieve the needed keys...

Please ensure your device is connected in DFU mode...
Traceback (most recent call last):
  File "./pyboot.py", line 505, in <module>
    main()
  File "./pyboot.py", line 477, in main
    img4.img4stuff(args.ios[0], args.ios[1], useCustomLogo, logopath, arewelocal, bootOtherOS, bootArgs, amfiPatches)
  File "/Users/efeemrullah/Desktop/PyBoot/resources/img4.py", line 245, in img4stuff
    pwndfumodeKeys()
  File "/Users/efeemrullah/Desktop/PyBoot/resources/pwn.py", line 32, in pwndfumodeKeys
    device = dfu.acquire_device()
  File "/Users/efeemrullah/Desktop/PyBoot/resources/ipwndfu/dfu.py", line 20, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Library/Python/3.8/site-packages/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Comment by efe-star** [comment]
OK. I solved the problem. "brew install libusb"
