### ISSUE TITLE
Failed to save SHSH?

### ISSUE THREAD

**Issue by Hzlyy** [MatthewPierson/PyBoot#8]
Last login: Sat Mar  7 01:27:26 on ttys000
123deMacBook-Pro:~ a123$ cd /Users/a123/Desktop/PyBoot-master 
123deMacBook-Pro:PyBoot-master a123$ ./pyboot.py -i iPad4,4 12.0
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i

Current version is: Beta 0.1
Make sure your device is connected in DFU mode
Checking theiphonewiki for 12.0 keys...
Traceback (most recent call last):
  File "./pyboot.py", line 202, in <module>
    main()
  File "./pyboot.py", line 182, in main
    img4.img4stuff(argv[2], argv[3], useCustomLogo, logopath)
  File "/Users/a123/Desktop/PyBoot-master/resources/img4.py", line 184, in img4stuff
    keys = wiki.getWikiKeys()
  File "/Users/a123/Desktop/PyBoot-master/resources/iospythontools/iphonewiki.py", line 42, in getWikiKeys
    buildid = oof.iOSToBuildid()
  File "/Users/a123/Desktop/PyBoot-master/resources/iospythontools/ipswapi.py", line 32, in iOSToBuildid
    self.linksForDevice('ipsw')
  File "/Users/a123/Desktop/PyBoot-master/resources/iospythontools/ipswapi.py", line 29, in linksForDevice
    return downloadJSONData(url, self.device)
  File "/Users/a123/Desktop/PyBoot-master/resources/iospythontools/utils.py", line 37, in downloadJSONData
    request = urlopen(url).read()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1322, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
123deMacBook-Pro:PyBoot-master a123$ ./pyboot.py -i iPad4,4 12.0
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i

Current version is: Beta 0.1
Make sure your device is connected in DFU mode
Checking theiphonewiki for 12.0 keys...
Found Keys!
Getting SHSH for signing images
ERROR: Failed to save shsh
123deMacBook-Pro:PyBoot-master a123$ ./pyboot.py -i iPad4,4 12.0
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i

Current version is: Beta 0.1
Make sure your device is connected in DFU mode
Checking theiphonewiki for 12.0 keys...
^Z
[1]+  Stopped                 ./pyboot.py -i iPad4,4 12.0
123deMacBook-Pro:PyBoot-master a123$ ./pyboot.py -i iPad4,4 12.0
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i

Current version is: Beta 0.1
Make sure your device is connected in DFU mode
Checking theiphonewiki for 12.0 keys...
^Z
[2]+  Stopped                 ./pyboot.py -i iPad4,4 12.0
123deMacBook-Pro:PyBoot-master a123$ ./pyboot.py -i iPad4,4 12.0
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i

Current version is: Beta 0.1
Make sure your device is connected in DFU mode
Checking theiphonewiki for 12.0 keys...
^Z
[3]+  Stopped                 ./pyboot.py -i iPad4,4 12.0
123deMacBook-Pro:PyBoot-master a123$ 
123deMacBook-Pro:PyBoot-master a123$ ./pyboot.py -i iPad4,4 12.0
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i

Current version is: Beta 0.1
Make sure your device is connected in DFU mode
Checking theiphonewiki for 12.0 keys...
^Z
[4]+  Stopped                 ./pyboot.py -i iPad4,4 12.0
123deMacBook-Pro:PyBoot-master a123$ ./pyboot.py -i iPad4,4 12.0
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i

Current version is: Beta 0.1
Make sure your device is connected in DFU mode
Checking theiphonewiki for 12.0 keys...
^Z
[5]+  Stopped                 ./pyboot.py -i iPad4,4 12.0
123deMacBook-Pro:PyBoot-master a123$ ./pyboot.py -i iPad4,4 12.0
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i

Current version is: Beta 0.1
Make sure your device is connected in DFU mode
Checking theiphonewiki for 12.0 keys...
Found Keys!
Getting SHSH for signing images
ERROR: Failed to save shsh
123deMacBook-Pro:PyBoot-master a123$

**Comment by Hzlyy** [comment]
s this shsh or shshsh2?
If I have a shsh2, 12.4.5, where should I put it?

**Comment by SIir-12** [comment]
Oh, it just like you run CMD in Windows without Administrator. Type sudo -s before running the program!
